"""add language toi
posts

Revision ID: 23183fb8b8e7
Revises: 8915ccf0da2a
Create Date: 2020-12-13 16:51:05.194651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23183fb8b8e7'
down_revision = '8915ccf0da2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
